/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adso39.vistas;

import com.adso39.contralodores.ControlUsuarios;
import com.adso39.modelos.Usuario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SENA
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());
    private ControlUsuarios elControlUsuarios;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        this.elControlUsuarios = new ControlUsuarios();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblidentificacion = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        cmbCargo = new javax.swing.JComboBox<>();
        ChbEsAdministrador = new javax.swing.JCheckBox();
        btnCapturarInformacion = new javax.swing.JButton();
        BtnCapturarInformacion2 = new javax.swing.JButton();
        BtnCapturarInformacion3 = new javax.swing.JButton();
        BtnCapturarInformacion4 = new javax.swing.JButton();
        btnCapturarInformacion5 = new javax.swing.JButton();
        btnAgregarUsuario = new javax.swing.JButton();
        btnListarUsuario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTextoAdmin = new javax.swing.JTextArea();
        btnConsultarUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Gestion de Usuarios");

        lblidentificacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblidentificacion.setText("Identificacion:");

        lblNombres.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombres.setText("Nombres:");

        lblApellidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblApellidos.setText("Apellidos");

        lblCargo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCargo.setText("Cargo:");

        lblAdmin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAdmin.setText("Es Administrador:");

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ChbEsAdministrador.setText("jCheckBox1");

        btnCapturarInformacion.setText("Capturar informacion");
        btnCapturarInformacion.addActionListener(this::btnCapturarInformacionActionPerformed);

        BtnCapturarInformacion2.setText("Capturar Informacion Objeto");
        BtnCapturarInformacion2.addActionListener(this::BtnCapturarInformacion2ActionPerformed);

        BtnCapturarInformacion3.setText("Capturar Informacion Obj-Constructor");
        BtnCapturarInformacion3.addActionListener(this::BtnCapturarInformacion3ActionPerformed);

        BtnCapturarInformacion4.setText("Capturar Informacion Obj-Control");
        BtnCapturarInformacion4.addActionListener(this::BtnCapturarInformacion4ActionPerformed);

        btnCapturarInformacion5.setText("Capturar Informacion- Obj control estatico");
        btnCapturarInformacion5.addActionListener(this::btnCapturarInformacion5ActionPerformed);

        btnAgregarUsuario.setText("Agregar Usuario");
        btnAgregarUsuario.addActionListener(this::btnAgregarUsuarioActionPerformed);

        btnListarUsuario.setText("Listar Usuario");
        btnListarUsuario.addActionListener(this::btnListarUsuarioActionPerformed);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblUsuarios);

        txtTextoAdmin.setColumns(20);
        txtTextoAdmin.setLineWrap(true);
        txtTextoAdmin.setRows(5);
        jScrollPane1.setViewportView(txtTextoAdmin);

        btnConsultarUsuarios.setText("Consultar Usuarios");
        btnConsultarUsuarios.addActionListener(this::btnConsultarUsuariosActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCapturarInformacion3))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAgregarUsuario))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblAdmin)
                                            .addGap(18, 18, 18)
                                            .addComponent(ChbEsAdministrador)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnListarUsuario)))
                                    .addGap(14, 14, 14)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(182, 182, 182)
                                    .addComponent(btnCapturarInformacion5))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BtnCapturarInformacion2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BtnCapturarInformacion4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnCapturarInformacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnConsultarUsuarios, javax.swing.GroupLayout.Alignment.TRAILING)))))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChbEsAdministrador)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(BtnCapturarInformacion2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnCapturarInformacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapturarInformacion5)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCapturarInformacion4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarUsuario)
                            .addComponent(btnCapturarInformacion))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultarUsuarios)
                            .addComponent(btnListarUsuario))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapturarInformacion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarInformacion5ActionPerformed
        // TODO add your handling code here:
        ControlUsuarios.RegistrarUsuario(txtIdentificacion.getText(),
            txtNombres.getText(),
            txtApellidos.getText(),
            cmbCargo.getSelectedIndex(),
            cmbCargo.getSelectedItem().toString(),
            ChbEsAdministrador.isSelected());

        txtTextoAdmin.setText(ControlUsuarios.ImprimirUsuario());
    }//GEN-LAST:event_btnCapturarInformacion5ActionPerformed

    private void BtnCapturarInformacion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCapturarInformacion4ActionPerformed

        this.elControlUsuarios.RegistrarUsuario(txtIdentificacion.getText(),

            txtNombres.getText(),
            txtApellidos.getText(),
            cmbCargo.getSelectedIndex(),
            cmbCargo.getSelectedItem().toString(),
            ChbEsAdministrador.isSelected());

        txtTextoAdmin.setText(this.elControlUsuarios.ImprimirUsuario());
    }//GEN-LAST:event_BtnCapturarInformacion4ActionPerformed

    private void BtnCapturarInformacion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCapturarInformacion3ActionPerformed
        Usuario elUsuario = new Usuario(txtIdentificacion.getText(),

            txtNombres.getText(),
            txtApellidos.getText(),
            cmbCargo.getSelectedIndex(),
            cmbCargo.getSelectedItem().toString(),
            ChbEsAdministrador.isSelected());

        txtTextoAdmin.setText(elUsuario.toString());
    }//GEN-LAST:event_BtnCapturarInformacion3ActionPerformed

    private void BtnCapturarInformacion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCapturarInformacion2ActionPerformed
        Usuario elUsuario = new Usuario();

        String identificacion = txtIdentificacion.getText();
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        int indiceCargo = cmbCargo.getSelectedIndex();
        String textoCargo = cmbCargo.getSelectedItem().toString();
        boolean esAdministrador = ChbEsAdministrador.isSelected();

        elUsuario.setIdentificacion(identificacion);
        elUsuario.setNombres(nombres);
        elUsuario.setApellidos(apellidos);
        elUsuario.setIndiceCargo(indiceCargo);
        elUsuario.setTextoCargo(textoCargo);
        elUsuario.setEsAdministrador(esAdministrador);

        txtTextoAdmin.setText(elUsuario.toString());
    }//GEN-LAST:event_BtnCapturarInformacion2ActionPerformed

    private void btnCapturarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarInformacionActionPerformed
        String identificacion = txtIdentificacion.getText();
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        int indiceCargo = cmbCargo.getSelectedIndex();
        String textoCargo = cmbCargo.getSelectedItem().toString();
        boolean esAdministrador = ChbEsAdministrador.isSelected();

        String textoMostrar = "Identificacion: " + identificacion + "\n" +
        "Nombre Completo: " + nombres +"" + apellidos + "\n" +
        "Cargo: (" + indiceCargo +")" + textoCargo + "\n" ;

        if(esAdministrador){
            textoMostrar += "El usuario no es administrador";
        }
        else{
            textoMostrar += "El usuario  es adminstrador";
        }
        txtTextoAdmin.setText(textoMostrar);
    }//GEN-LAST:event_btnCapturarInformacionActionPerformed

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        // TODO add your handling code here:
        ControlUsuarios.AgregarUsuario(txtIdentificacion.getText(), 
                txtNombres.getText(), 
                txtApellidos.getText(), 
                cmbCargo.getSelectedIndex(),
                cmbCargo.getSelectedItem().toString(),
                ChbEsAdministrador.isSelected());
        
        txtTextoAdmin.setText("Agregado:\n" +
                txtNombres.getText() +
                " " +
                txtApellidos.getText());
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void btnListarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarUsuarioActionPerformed
        // TODO add your handling code here:
        txtTextoAdmin.setText(ControlUsuarios.ListarUsuarios());
    }//GEN-LAST:event_btnListarUsuarioActionPerformed

    private void btnConsultarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarUsuariosActionPerformed
        // TODO add your handling code here:
        
        ArrayList<Usuario> losUsuarios = ControlUsuarios.MostrarUsuarios();
        /*
        "(identificacion, nombres, apellidos, "+
                "indicecargo, textocargo, esAdministrador) "+
        */
        DefaultTableModel modeloUsuarios = new DefaultTableModel();
        modeloUsuarios.addColumn("Identificacion");
        modeloUsuarios.addColumn("Nombre Completo");
        modeloUsuarios.addColumn("Es Administrador");
        for (int index = 0;
                index<losUsuarios.size();
                index++){
                Object[] fila = new Object[3];
                fila[0] = losUsuarios.get(index).getIdentificacion();
                fila[1] = losUsuarios.get(index).getNombres() + " " + losUsuarios.get(index).getApellidos();
                if (losUsuarios.get(index).isEsAdministrador()) {
                    fila [2] = "si";
                } else {
                    fila [2] = "No";
                  
                }
                modeloUsuarios.addRow(fila);
                
                }
        tblUsuarios.setModel(modeloUsuarios);
    }//GEN-LAST:event_btnConsultarUsuariosActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCapturarInformacion2;
    private javax.swing.JButton BtnCapturarInformacion3;
    private javax.swing.JButton BtnCapturarInformacion4;
    private javax.swing.JCheckBox ChbEsAdministrador;
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnCapturarInformacion;
    private javax.swing.JButton btnCapturarInformacion5;
    private javax.swing.JButton btnConsultarUsuarios;
    private javax.swing.JButton btnListarUsuario;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblidentificacion;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextArea txtTextoAdmin;
    // End of variables declaration//GEN-END:variables
}
